# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=0.4.3
maven_group=com.glisco
archives_base_name=deathlog

# Dependencies
fabric_api_version=0.158.0+26.2

# https://github.com/emilyploszaj/trinkets/releases
trinkets_version=3.10.0

# https://maven.ladysnake.org/#/releases/dev/onyxstudios/cardinal-components-api/cardinal-components-api/cardinal-components-base
cca_version=6.2.0

# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
modmenu_version=20.0.1

# https://maven.wispforest.io/io/wispforest/owo-lib/
owo_version=0.13.1+26.2